server:
  port: 8088

spring:
  profiles:
    active: dev # 默认激活 dev 本地开发环境

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

# MQ 消费者
mq-consumer:
  follow-unfollow: # 关注、取关
    rate-limit: 5000 # 每秒限流阈值
