name: licht-music-backend

services:
  nacos:
    image: nacos/nacos-server:latest
    environment:
      MODE: standalone
      NACOS_AUTH_ENABLE: true
      NACOS_AUTH_IDENTITY_KEY: root
      NACOS_AUTH_IDENTITY_VALUE: 20240414
      NACOS_AUTH_TOKEN: dkJKMVlETlhQcVgyNTl3OEJNd0oza3RkZDZEdXVrRVk=
    networks:
      - licht-music-backend
    ports:
      - "8848:8848"
      - "9848:9848"
    volumes:
      - E:/volumes/nacos:/home/nacos/data

  zookeeper:
    image: zookeeper:latest
    command: zkServer.sh start-foreground
    environment:
      TZ: Asia/Shanghai
    networks:
      - licht-music-backend
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
      - "8083:8080"
    volumes:
      - E:/volumes/zookeeper/conf:/conf
      - E:/volumes/zookeeper/data:/data
      - E:/volumes/zookeeper/logs:/logs
      - E:/volumes/zookeeper/datalog:/datalog

  mysql:
    image: mysql:lts
    command: mysqld --mysql-native-password
    environment:
      MYSQL_ROOT_PASSWORD: 20240414
    networks:
      - licht-music-backend
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - E:/volumes/mysql/data:/var/lib/mysql

  cassandra:
    image: cassandra:latest
    command: cassandra -f
    networks:
      - licht-music-backend
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    volumes:
      - E:/volumes/cassandra:/var/lib/cassandra

  redis:
    image: redis/redis-stack-server:latest
    environment:
      REDIS_ARGS: --appendonly yes --requirepass 20240414
    networks:
      - licht-music-backend
    ports:
      - "6379:6379"
    volumes:
      - E:/volumes/redis:/data

  minio:
    image: minio/minio:latest
    command: minio server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 20240414
    networks:
      - licht-music-backend
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - E:/volumes/minio:/data

  rocketmq-namesrv:
    image: apache/rocketmq:latest
    command: sh mqnamesrv
    networks:
      - licht-music-backend
    ports:
      - "9876:9876"

  rocketmq-broker:
    image: apache/rocketmq:latest
    command: sh mqbroker -c /home/rocketmq/conf/broker.conf
    environment:
      NAMESRV_ADDR: rocketmq-namesrv:9876
    depends_on:
      - rocketmq-namesrv
    networks:
      - licht-music-backend
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    volumes:
      - E:/volumes/rocketmq/conf/broker.conf:/home/rocketmq/conf/broker.conf

  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.2
    environment:
      PARAMS: --server.port=7777 --spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=20240414 --spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      - licht-music-backend
    ports:
      - "7777:7777"

  elasticsearch:
    image: elasticsearch:7.17.26
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms1024m -Xmx1024m
    networks:
      - licht-music-backend
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - E:/volumes/elasticsearch/data:/usr/share/elasticsearch/data
      - E:/volumes/elasticsearch/plugins:/usr/share/elasticsearch/plugins

  kibana:
    image: kibana:7.17.26
    environment:
      I18N_LOCALE: zh-CN
    networks:
      - licht-music-backend
    ports:
      - "5601:5601"
    volumes:
      - E:/volumes/kibana/data:/usr/share/kibana/data

  #  logstash:
  #    image: logstash:7.17.26
  #    networks:
  #      - licht-music-backend
  #    volumes:
  #      - E:/volumes/logstash/data:/usr/share/logstash/data
  #      - E:/volumes/logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
  #      - E:/volumes/logstash/pipeline:/usr/share/logstash/pipeline

  canal:
    image: canal/canal-server:latest
    environment:
      canal.destinations: search
      canal.instance.master.address: mysql:3306
      canal.instance.dbUsername: canal
      canal.instance.dbPassword: 20240414
    networks:
      - licht-music-backend
    ports:
      - "11110:11110"
      - "11111:11111"
      - "11112:11112"
      - "9100:9100"


networks:
  licht-music-backend:
    driver: bridge